name: Call API Hourly

on:
  schedule:
    # Cron syntax is strange, but don't worry! It's very simple to use
    # A great reference and checker is https://crontab.guru/
    # This won't run til 2023
    - cron: 1 1 1 1 1

jobs:
  ping-api:
    # Windows and macos are also options, as well as self-hosted runners
    # Generally, ubuntu-latest is what you want to use
    runs-on: ubuntu-latest
    steps:
      # No checkout step here, we don't need it!
      - name: Call out to API with pangram
        env:
          # Normally we wouldn't want a constant value here
          # For the purposes of this exercise, though, it's acceptable
          API_URL: 'https://yourapiurlthi.ng'
        # We'll keep it simple and use curl, a basic unix utility
        run: curl $API_URL

      - name: Call out to API with non-pangram
        env:
          API_URL: 'https://yourapiurlthi.ng'
        run: curl $API_URL
        
    # What else might we do here? 