name: Check package.json on PR Open/Updated

# Triggers on a PR open or when commit(s) add(ed)
on:
  schedule:
    # Cron syntax is strange, but don't worry! It's very simple to use
    # A great reference and checker is https://crontab.guru/
    - cron: 0 * * * *

jobs:
  ping-api:
    # Windows and macos are also options, as well as self-hosted runners
    # Generally, ubuntu-latest is what you want to use
    runs-on: ubuntu-latest
    steps:
      # No checkout step here, we don't need it!
      - name: Call out to API with pangram
        env:
          # Normally we wouldn't want a constant value here
          # For the purposes of this exercise, though, it's acceptable
          API_URL: 'https://rgt26hbfag.execute-api.us-west-2.amazonaws.com/v0/pangram?string=abcdefghijklmnopqrstuvwxyz'
        # We'll keep it simple and use curl, a basic unix utility
        run: curl $API_URL

      - name: Call out to API with non-pangram
        env:
          API_URL: 'https://rgt26hbfag.execute-api.us-west-2.amazonaws.com/v0/pangram?string=abcd'
        run: curl $API_URL
        
    # What else might we do here? 